[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/health"
healthcheckTimeout = 100

# Environment variables
[variables]
# Use Railway's variable substitution to reference the MongoDB service
MONGO_URL = "${{ MongoDB.MONGO_URL }}"
MONGO_PUBLIC_URL = "${{ MongoDB.MONGO_PUBLIC_URL }}"
# Keep JWT_SECRET directly defined since it's not from another service
JWT_SECRET = "HMteGawXDysvMBXBEXCeDKVBJuLrFyal"
NODE_ENV = "production"
